import { db } from '../../../system/db/data.js';
import { runtime } from '../../../system/function.js';

export default function(ev) {
    ev.on({
        name: 'report',
        cmd: ['bug'],
        tags: 'Main Menu',
        desc: 'Laporkan masalah/bug ke Owner (Auto PDF)',
        run: async (xp, m, { text }) => {
            if (!text) return m.reply(`⚠️ Masukkan detail masalah/laporan Anda.\nContoh: *.report* Fitur download tiktok error gan.`)

            await m.reply('📝 *Membuat Laporan PDF...*')

            const pdfkit = await import('pdfkit');
            const PDFDocument = pdfkit.default || pdfkit;

            try {
                // --- USER DATA ---
                const user = db().key[Object.keys(db().key).find(k => db().key[k].jid === m.sender)] || {}
                const name = m.pushName || user.name || 'Unknown User'
                const date = new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })
                const reportId = `RPT-${Date.now().toString().slice(-6)}`

                // --- CREATE PDF ---
                const doc = new PDFDocument({ size: 'A4', margin: 50 });
                const buffers = [];
                doc.on('data', buffers.push.bind(buffers));
                
                doc.on('end', async () => {
                    const pdfBuffer = Buffer.concat(buffers);
                    const ownerJid = global.ownerNumber[0].replace(/[^0-9]/g, '') + '@s.whatsapp.net'
                    
                    // 1. Kirim ke Owner
                    await xp.sendMessage(ownerJid, {
                        document: pdfBuffer,
                        mimetype: 'application/pdf',
                        fileName: `${reportId}.pdf`,
                        caption: `📩 *LAPORAN BARU DITERIMA*\n\nDari: @${m.sender.split('@')[0]}\nID: ${reportId}`,
                        contextInfo: { mentions: [m.sender] }
                    })
                    
                    // 2. Reply User
                    await xp.sendMessage(m.chat, { text: `✅ *Laporan Terkirim!* \nID Tiket: ${reportId}\nTerima kasih atas masukan Anda.` }, { quoted: m })
                });

                // --- PDF DESIGN (PROFESSIONAL) ---
                
                // Header Background
                doc.rect(0, 0, 600, 100).fill('#1e293b'); // Dark Blue Header
                
                // Title
                doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold')
                   .text('BUG REPORT TICKET', 50, 40);
                
                doc.fontSize(10).font('Helvetica')
                   .text(`Generated by ${global.botName}`, 50, 70);

                // Report ID Badge
                doc.roundedRect(450, 35, 100, 30, 5).fill('#ef4444'); // Red Badge
                doc.fillColor('#ffffff').fontSize(12).font('Helvetica-Bold')
                   .text(reportId, 450, 45, { width: 100, align: 'center' });

                // Reset Color
                doc.fillColor('#000000').moveDown(4);

                // --- REPORTER INFO ---
                doc.fontSize(14).font('Helvetica-Bold').text('👤 REPORTER INFORMATION');
                doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cbd5e1').lineWidth(2).stroke().moveDown(0.5);
                
                const info = [
                    { label: 'Name', value: name },
                    { label: 'WhatsApp ID', value: m.sender.split('@')[0] },
                    { label: 'Date/Time', value: date },
                    { label: 'Status', value: user.premium ? 'Premium User' : 'Free User' },
                    { label: 'Limit', value: `${user.limit || 0}` }
                ];

                info.forEach(item => {
                    doc.fontSize(10).font('Helvetica-Bold').fillColor('#475569').text(item.label, { continued: true, width: 100 });
                    doc.font('Helvetica').fillColor('#000000').text(`:  ${item.value}`);
                    doc.moveDown(0.2);
                });
                doc.moveDown(2);

                // --- REPORT CONTENT ---
                doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text('📝 REPORT DETAIL');
                doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#cbd5e1').lineWidth(2).stroke().moveDown(1);
                
                // Box for content
                const contentY = doc.y;
                doc.rect(50, contentY, 500, 200).fillAndStroke('#f8fafc', '#94a3b8');
                
                doc.fillColor('#334155').fontSize(12).font('Helvetica')
                   .text(text, 60, contentY + 10, { width: 480, align: 'left' });

                doc.moveDown(15);

                // Footer
                doc.fontSize(10).font('Helvetica-Oblique').fillColor('#94a3b8')
                   .text('Automated Report System', 50, 750, { align: 'center' });

                doc.end();

            } catch (e) {
                console.error("Report Error:", e);
                m.reply("❌ Gagal membuat laporan.");
            }
        }
    });
}